src/models/usuario.py
from database import conexion_database

#modelo Usuario
class Usuario:
    
    @staticmethod  # Método para obtener los usuarios de la base de datos
    def obtener_usuarios():
        cursor = conexion_database.cursor()
        cursor.execute("SELECT id, nombre_usuario, apellido_usuario, correo FROM usuarios;")
        resultados = cursor.fetchall()
        cursor.close()
        return resultados

    @staticmethod  # Método para crear un nuevo usuario
    def insertar_usuario(nombre, apellido, correo, contrasenia):
        cursor = conexion_database.cursor()
        sql_query_insertar = "INSERT INTO usuarios (nombre_usuario, apellido_usuario, correo, contrasenia) VALUES (%s, %s, %s, %s)"
        data_insertar = (nombre, apellido, correo, contrasenia)
        cursor.execute(sql_query_insertar, data_insertar)
        conexion_database.commit()
        cursor.close()

    @staticmethod  # Método para eliminar un usuario
    def eliminar_usuario(id):
        cursor = conexion_database.cursor()
        sql_query_eliminar = "DELETE FROM usuarios WHERE id = %s"
        data = (id,)
        cursor.execute(sql_query_eliminar, data)
        conexion_database.commit()
        cursor.close()
        
    @staticmethod  # Método para actualizar datos del usuario
    def actualizar_usuario(id,nombre, apellido,correo):
        cursor = conexion_database.cursor()
        sql_query_editar = "UPDATE usuarios SET nombre_usuario = %s, apellido_usuario = %s, correo = %s WHERE id = %s"
        data_actualizada = (nombre, apellido, correo, id)
        cursor.execute(sql_query_editar, data_actualizada)
        conexion_database.commit()
        cursor.close()
        
        
        
        
        
        
        

src/app.py
from flask import Flask
# from src.controllers.usuario_controller import usuario_bp
from controllers.usuario_controller import usuario_bp
import os


# Inicialización de la aplicación Flask
template_dir = os.path.join(os.path.abspath(os.path.dirname(__file__)), 'templates')
app = Flask(__name__, template_folder=template_dir)

# Registro del Blueprint
app.register_blueprint(usuario_bp)

if __name__ == '__main__':
    app.run(debug=True, port=4000)

src/controllers/usuario_controller.py
# src/controllers/usuario_controller.py
from flask import Blueprint, render_template, redirect, request, url_for
from models.usuario import Usuario

usuario_bp = Blueprint('usuario_bp', __name__)

# Ruta de la Aplicación
@usuario_bp.route('/')
def home():
    usuarios = Usuario.obtener_usuarios()
    # Convertir los datos de Resultados a Diccionario
    insertObject = []
    columnNames = ['id', 'nombre_usuario', 'apellido_usuario', 'correo']
    for record in usuarios:
        insertObject.append(dict(zip(columnNames, record)))  # Emparejando cada nombre de columna a su datos
    return render_template('index.html', datos=insertObject)

# Ruta para guardar usuarios en la base de datos
@usuario_bp.route('/usuarios', methods=['POST'])
def guardarUsuarios():
    nombre = request.form['nombre_usuario']
    apellido = request.form['apellido_usuario']
    correo = request.form['correo']
    contrasenia = request.form['contrasenia']
    
    if nombre and apellido and correo and contrasenia:
        Usuario.insertar_usuario(nombre, apellido, correo, contrasenia)
        
    return redirect(url_for('usuario_bp.home'))

# Ruta para eliminar un usuario
@usuario_bp.route('/delete/<string:id>')
def eliminarUsuario(id):
    Usuario.eliminar_usuario(id)
    return redirect(url_for('usuario_bp.home'))


#  Ruta para editar un Usuario
@usuario_bp.route('/edit/<string:id>', methods = ['POST'])
def editarUsuario(id):
    nombre = request.form['nombre_usuario']
    apellido = request.form['apellido_usuario']
    correo = request.form['correo']
    
    if nombre and apellido and correo:
        Usuario.actualizar_usuario(id,nombre, apellido, correo)
    return redirect(url_for('usuario_bp.home'))

src/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CRUD Example</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <style>
        body {
            background-color: #afe2fc; /* Gris suave */
        }
        .btn-color-visualizar {
            background-color: #0055fe; /* Color azul personalizado */
            color: rgb(255, 255, 255);
        }
        .btn-color-editar{
            background-color: #ffff00; /* Color azul personalizado */
            color: rgb(0, 0, 0);
        }
        .btn-color-eliminar{
            background-color: #e50000d5; /* Color azul personalizado */
            color: rgb(0, 0, 0);
        }
    </style>
</head>
<body>
    
    <h1 class="text-center mt-5 mb-5 fs-2 fw-bold">CRUD-MVC-Python-Flask-MySQL</h1>
    <div class="container">
        <div class="card  shadow">
            <div class="card-body ">
                <form action="/usuarios" method="POST">
                    <div class="row mb-3">
                        <div class="col-md-3">
                            <label>Nombre de Usuario</label>
                            <input type="text" class="form-control mb-3" name="nombre_usuario">
                        </div>
                        <div class="col-md-3">
                            <label>Apellido de Usuario</label>
                            <input type="text" class="form-control mb-3" name="apellido_usuario">
                        </div>
                        <div class="col-md-3">
                            <label>Correo</label>
                            <input type="email" class="form-control mb-3" name="correo">
                        </div>
                        <div class="col-md-3">
                            <label>Contraseña del Usuario</label>
                            <input type="password" class="form-control mb-3" name="contrasenia">
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col d-grid gap-2 col-6 mx-auto">
                            <button class="btn btn-primary" type="submit">Guardar</button>
                        </div>
                    </div>
                </form>

                <!-- Tabla -->
    
                <table class="table table-bordered table-striped text-secondary bg-dark">
                    <thead class="table-dark">
                        <th scope="col">#</th>
                        <th scope="col">Nombre de Usuario</th>
                        <th scope="col">Apellido de Usuario</th>
                        <th scope="col">Correo</th>
                        <th scope="col">Vizualizar</th>
                        <th scope="col">Editar</th>
                        <th scope="col">Borrar</th>
                    </thead>

                    <tbody>
                        {% for d in datos %}
                            <tr>
                                <td> {{d.id}} </td>
                                <td> {{d.nombre_usuario}}</td>
                                <td> {{d.apellido_usuario}} </td>
                                <td> {{d.correo}} </td>
                                <td><button class="btn btn-color-visualizar btn-sm bi bi-eye" data-bs-toggle="modal" data-bs-target="#modal{{d.nombre_usuario}}"> Visualizar</button></td>
                                <td> <button class="btn btn-color-editar btn-sm bi bi-pencil" id="btn-edit{{d.id}}" data-bs-toggle="modal" data-bs-target="#modal{{d.id}}"> Editar</button></td>
                                <td><a href=" {{url_for('usuario_bp.eliminarUsuario', id=d.id)}} " class="btn btn-color-eliminar btn-sm bi bi-trash"> Eliminar</a></td>
                            </tr>

                            <!--MODAL Para Editar Datos -->

                            <div class="modal fade" id="modal{{d.id}}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h1 class="modal-title fs-5" id="exampleModalLabel"> {{d.nombre_usuario}} </h1>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body">
                                            <form action="/edit/{{d.id}}" method="post">
                                                <label>Nombre de Usuario: {{d.nombre_usuario}}</label>
                                                <input type="text" class="form-control mb-3" name="nombre_usuario" value="{{d.nombre_usuario}}">
                                                <label>Apellido de Usuario</label>
                                                <input type="text" class="form-control mb-3" name="apellido_usuario" value="{{d.apellido_usuario}}">
                                                <label>Correo</label>
                                                <input type="email" class="form-control mb-3" name="correo" value="{{d.correo}}">
                                        </div>
                                        <div class="modal-footer">
                                            <button type="submit" class="btn btn-primary">Guardar Cambios</button>
                                        </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                            <!--Modal Visualizar Datos-->
                            <div class="modal fade" id="modal{{d.nombre_usuario}}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h1 class="modal-title fs-5" id="exampleModalLabel"> Visualizar datos: {{d.nombre_usuario}} </h1>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body">
                                            <form method="post">
                                                <label>Nombre de Usuario: {{d.nombre_usuario}}</label><br>
                                                <label>Apellido de Usuario: {{d.apellido_usuario}}</label><br>
                                                <label>Correo: {{d.correo}}</label><br>
                                        </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                            
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</body>
</html>